# Generated by Django 3.2.7 on 2021-10-21 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread', # モデル名
            old_name='thread_text',   # 変更前
            new_name='title'    # 変更後
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='favorite_num',
            new_name='favorites',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='latest_date',
            new_name='update_date',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='response_text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='tweet_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='name_text',
            new_name='name',
        ),
    ]
