# Generated by Django 3.2.7 on 2021-10-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20211021_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='trip',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
    ]
