# Generated by Django 3.2.7 on 2021-10-16 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20211016_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='name_str',
            new_name='name_text',
        ),
    ]
