# Generated by Django 3.2.7 on 2021-10-16 07:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_rename_name_str_response_name_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='latest_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 16, 7, 2, 54, 350435, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
