# Generated by Django 3.2.7 on 2021-10-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_response_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
