# Generated by Django 3.2.7 on 2021-10-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_thread_latest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='favorite_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
