# Generated by Django 3.2.7 on 2021-10-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_thread_favorite_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='hash_text',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
