# Generated by Django 3.2.7 on 2021-10-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='responses',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
