# Generated by Django 3.2.7 on 2021-12-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_thread_responses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='content',
            field=models.TextField(max_length=255),
        ),
    ]
