# Generated by Django 3.2.7 on 2021-10-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_response_hash_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='ng_text',
            field=models.CharField(default='NG WORD', max_length=255, verbose_name='NG WORD'),
            preserve_default=False,
        ),
    ]
