# Generated by Django 3.2.7 on 2021-10-19 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_response_ng_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='ng_text',
        ),
    ]
