# Generated by Django 3.2.8 on 2021-12-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_alter_response_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='content',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='response',
            name='name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(max_length=32),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
